### PR TITLE
Adding script to upload to google storage

### PR DESCRIPTION
**Pull request by vsoch**
This will add a script to make it easy for the user to upload the testing data to Google Cloud Storage. It will be referenced in upcoming tutorials for the Google Life Sciences AP (upcoming!) :) The PR includes:

 - the script, named to indicate exactly what it does, "upload_google_storage.py"
 - documentation for usage in the README, with expected command line output
 - an image to show the files in storage

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
@johanneskoester we probably want to get this merged, and then link directly to it (and the Snakefile) from the Google Life Sciences tutorial.

**Review by johanneskoester — APPROVED** [review]

**Comment by aryarm** [comment]
@vsoch I think there's [a stray IPython import](https://github.com/snakemake/snakemake-tutorial-data/commit/03c1e50a787e8d9501509453fd3b7730116ac4f1#diff-845920a95676e8127db46ca1f04a4fb4R92) in `upload_google_storage.py`. Nothing to worry too much about, but I thought I'd mention it here just in case! Things still seem to work when lines 92-94 are deleted.

**Comment by vsoch** [comment]
oy vey! Let me remove it asap.

**Comment by vsoch** [comment]
See https://github.com/snakemake/snakemake-tutorial-data/pull/4

**Pull request merged**
